import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { createInterface } from 'node:readline';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';

test('bundled MCP advertises completion and explicit artifact tools', async t => {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
  const directory = await mkdtemp(path.join(os.tmpdir(), 'notify-mcp-'));
  const artifact = path.join(directory, 'result.txt');
  await writeFile(artifact, 'done');
  t.after(() => rm(directory, { recursive: true, force: true }));
  const child = spawn(process.execPath, ['--import', 'tsx', path.join(root, 'src', 'notify-mcp.ts')], { stdio: ['pipe', 'pipe', 'pipe'], windowsHide: true });
  t.after(() => child.kill());
  const lines = createInterface({ input: child.stdout, crlfDelay: Infinity });
  const replies: any[] = [];
  lines.on('line', line => replies.push(JSON.parse(line)));
  const send = (value: unknown) => child.stdin.write(`${JSON.stringify(value)}\n`);
  send({ jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-03-26' } });
  send({ jsonrpc: '2.0', method: 'notifications/initialized' });
  send({ jsonrpc: '2.0', id: 2, method: 'tools/list', params: {} });
  send({ jsonrpc: '2.0', id: 3, method: 'tools/call', params: { name: 'request_feishu_completion_notification', arguments: { summary: '开发通知功能' } } });
  send({ jsonrpc: '2.0', id: 4, method: 'tools/call', params: { name: 'send_artifact_to_feishu', arguments: { paths: [artifact] } } });
  send({ jsonrpc: '2.0', id: 5, method: 'tools/call', params: { name: 'send_artifact_to_feishu', arguments: { paths: [directory] } } });
  for (let count = 0; count < 100 && replies.length < 5; count++) await new Promise(resolve => setTimeout(resolve, 10));
  assert.equal(replies[0]?.result.serverInfo.name, 'feishu-codex-notify');
  assert.equal(replies[1]?.result.tools[0].name, 'request_feishu_completion_notification');
  assert.equal(replies[1]?.result.tools[1].name, 'send_artifact_to_feishu');
  assert.match(replies[1]?.result.tools[0].description, /不同表达/);
  assert.match(replies[2]?.result.content[0].text, /已登记/);
  assert.equal(replies[2]?.result.isError, false);
  const artifactReply = replies.find(reply => reply.id === 4);
  assert.deepEqual(artifactReply?.result.structuredContent.paths, [await import('node:fs/promises').then(module => module.realpath(artifact))]);
  assert.match(artifactReply?.result.content[0].text, /已提交 1 个/);
  assert.match(replies.find(reply => reply.id === 5)?.error.message ?? '', /not a regular file/);
});
